In [7]:
import pandas as pd

emails = ["anita.dev@corp.com", "rahul.hr@corp.com", "sales.team@corp.com",
"meera.data@corp.com", "vikram.hr@corp.in", "priya.ops@corp.com"]

email_series = pd.Series(emails, name="emails")
email_series

0     anita.dev@corp.com
1      rahul.hr@corp.com
2    sales.team@corp.com
3    meera.data@corp.com
4      vikram.hr@corp.in
5     priya.ops@corp.com
Name: emails, dtype: object

In [8]:
codes = ["ENG-101", "MKT-205", "SAL-330", "HR-118", "ENG-202","OPS-404"]

code_series = pd.Series(codes, name="codes")
code_series

0    ENG-101
1    MKT-205
2    SAL-330
3     HR-118
4    ENG-202
5    OPS-404
Name: codes, dtype: object

In [11]:
print(email_series.str.contains("hr"))
print('---------')
email_series[email_series.str.contains("hr")]

0    False
1     True
2    False
3    False
4     True
5    False
Name: emails, dtype: bool
---------

1    rahul.hr@corp.com
4    vikram.hr@corp.in
Name: emails, dtype: object

In [12]:
email_series.str.startswith("a")

0     True
1    False
2    False
3    False
4    False
5    False
Name: emails, dtype: bool

In [14]:
email_series.str.endswith(".com")

0     True
1     True
2     True
3     True
4    False
5     True
Name: emails, dtype: bool

In [18]:
email_series.str.slice(1, 3)

0    ni
1    ah
2    al
3    ee
4    ik
5    ri
Name: emails, dtype: object

In [21]:
email_series.str.slice(-3)

0    com
1    com
2    com
3    com
4    .in
5    com
Name: emails, dtype: object

In [23]:
code_series.str.split("-")

0    [ENG, 101]
1    [MKT, 205]
2    [SAL, 330]
3     [HR, 118]
4    [ENG, 202]
5    [OPS, 404]
Name: codes, dtype: object

In [24]:
code_series.str.split("-", expand=True)

     0    1
0  ENG  101
1  MKT  205
2  SAL  330
3   HR  118
4  ENG  202
5  OPS  404

In [25]:
email_series.str.split("@", expand=True)

            0         1
0   anita.dev  corp.com
1    rahul.hr  corp.com
2  sales.team  corp.com
3  meera.data  corp.com
4   vikram.hr   corp.in
5   priya.ops  corp.com

In [26]:
email_series.str.count("com")

0    1
1    1
2    1
3    1
4    0
5    1
Name: emails, dtype: int64